import csv
import io

class ValidationService:
    def __init__(self, lang_source, lang_target):
        self.lang_source = lang_source
        self.lang_target = lang_target
        # Keep track of words we've already seen to prevent cross-category duplicates
        self.seen_lemmas = set()
        self.seen_foreign_words = set()

    def process_chunk(self, raw_csv_text: str) -> list[str]:
        """
        Parses the raw CSV text generated by AI, validates it, deduplicates it, 
        and returns a list of valid CSV rows (strings).
        """
        valid_rows = []
        
        # Read the raw text as a CSV
        reader = csv.reader(io.StringIO(raw_csv_text), delimiter=';')
        
        for index, row in enumerate(reader):
            # 1. Column count validation
            if len(row) < 8:
                # Some rows might have trailing empty columns omitted by the LLM
                # Pad to 8 if it's missing trailing empty columns, else reject
                if len(row) >= 7:
                    row.extend([''] * (8 - len(row)))
                else:
                    print(f"  [Validator] Rejecting row (insufficient columns {len(row)}/8): {';'.join(row)}")
                    continue
                    
            if len(row) > 8:
                # Trim to 8 if there are extra trailing semicolons
                row = row[:8]

            foreign_word = row[0].strip()
            ukrainian_word = row[1].strip()
            plural = row[2].strip()
            category_tag = row[3].strip()
            lemma = row[4].strip()
            lemma_translation = row[5].strip()
            part_of_speech = row[6].strip()
            transliteration = row[7].strip()

            # 2. Empty/Missing essential fields
            if not foreign_word or not ukrainian_word or not lemma or not part_of_speech or not category_tag:
                print(f"  [Validator] Rejecting row (missing essential fields): {';'.join(row)}")
                continue

            # 3. Deduplication Check
            # We track lemmas and raw foreign words to prevent duplicates
            unique_key_lemma = lemma.lower()
            unique_key_foreign = foreign_word.lower()
            
            if unique_key_lemma in self.seen_lemmas or unique_key_foreign in self.seen_foreign_words:
                print(f"  [Validator] Rejecting duplicate word: {foreign_word} (lemma: {lemma})")
                continue
                
            # 4. Linguistic Consistency Checks
            # Very basic checks depending on language
            if self.lang_source == "de":
                # German nouns should have der/die/das
                if part_of_speech == "noun" and not any(foreign_word.startswith(art + " ") for art in ["der", "die", "das"]):
                    print(f"  [Validator] Warning: German noun missing article: {foreign_word}")
                    
            elif self.lang_source == "pl":
                # Polish verbs usually end with ć/c/ź
                if "verb" in part_of_speech.lower() and not lemma.endswith(("ć", "c", "ź")):
                    print(f"  [Validator] Warning: Polish verb lemma might be incorrect: {lemma}")

            # Register as seen
            self.seen_lemmas.add(unique_key_lemma)
            self.seen_foreign_words.add(unique_key_foreign)

            # Reconstruct the valid row
            valid_row_str = ";".join([
                foreign_word,
                ukrainian_word,
                plural,
                category_tag,
                lemma,
                lemma_translation,
                part_of_speech,
                transliteration
            ])
            valid_rows.append(valid_row_str)

        return valid_rows
